/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.contador.iu;

import br.com.contador.controle.decTObin;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author fe_li
 */
public class painel extends javax.swing.JFrame {

    /**
     * Creates new form painel
     */
    public painel() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBhora0 = new javax.swing.JCheckBox();
        CBhora1 = new javax.swing.JCheckBox();
        CBhora2 = new javax.swing.JCheckBox();
        CBhora3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        CBhora4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        CBminuto0 = new javax.swing.JCheckBox();
        CBminuto1 = new javax.swing.JCheckBox();
        CBminuto2 = new javax.swing.JCheckBox();
        CBminuto3 = new javax.swing.JCheckBox();
        CBminuto4 = new javax.swing.JCheckBox();
        CBminuto5 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        JCK_seg_2 = new javax.swing.JCheckBox();
        JCK_seg_3 = new javax.swing.JCheckBox();
        JCK_seg_4 = new javax.swing.JCheckBox();
        JCK_seg_5 = new javax.swing.JCheckBox();
        JCK_seg_0 = new javax.swing.JCheckBox();
        JCK_seg_1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CBhora0.setText("16");
        CBhora0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBhora0ActionPerformed(evt);
            }
        });

        CBhora1.setText("8");
        CBhora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBhora1ActionPerformed(evt);
            }
        });

        CBhora2.setText("4");

        CBhora3.setText("2");
        CBhora3.setToolTipText("");

        jLabel1.setText("Hora");

        CBhora4.setText("1");

        jLabel2.setText("minutos");

        CBminuto0.setText("32");
        CBminuto0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBminuto0ActionPerformed(evt);
            }
        });

        CBminuto1.setText("16");
        CBminuto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBminuto1ActionPerformed(evt);
            }
        });

        CBminuto2.setText("8");

        CBminuto3.setText("4");

        CBminuto4.setText("2");

        CBminuto5.setText("1");

        jLabel3.setText("Segundos");

        JCK_seg_2.setText("8");

        JCK_seg_3.setText("4");

        JCK_seg_4.setText("2");

        JCK_seg_5.setText("1");
        JCK_seg_5.setToolTipText("Segundos");
        JCK_seg_5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        JCK_seg_5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        JCK_seg_0.setText("32");
        JCK_seg_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCK_seg_0ActionPerformed(evt);
            }
        });

        JCK_seg_1.setText("16");
        JCK_seg_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCK_seg_1ActionPerformed(evt);
            }
        });

        jButton1.setText("inicia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBminuto0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBminuto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBminuto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBminuto3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBminuto4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBminuto5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCK_seg_0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCK_seg_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCK_seg_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCK_seg_3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCK_seg_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCK_seg_5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBhora0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBhora1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBhora2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBhora3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBhora4))
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBhora0)
                    .addComponent(CBhora1)
                    .addComponent(CBhora2)
                    .addComponent(CBhora3)
                    .addComponent(CBhora4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBminuto0)
                    .addComponent(CBminuto1)
                    .addComponent(CBminuto2)
                    .addComponent(CBminuto3)
                    .addComponent(CBminuto4)
                    .addComponent(CBminuto5))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCK_seg_0)
                    .addComponent(JCK_seg_1)
                    .addComponent(JCK_seg_2)
                    .addComponent(JCK_seg_3)
                    .addComponent(JCK_seg_4)
                    .addComponent(JCK_seg_5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBhora0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBhora0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBhora0ActionPerformed

    private void CBhora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBhora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBhora1ActionPerformed

    private void CBminuto0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBminuto0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBminuto0ActionPerformed

    private void CBminuto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBminuto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBminuto1ActionPerformed

    private void JCK_seg_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCK_seg_0ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCK_seg_0ActionPerformed

    private void JCK_seg_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCK_seg_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCK_seg_1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        decTObin bin = new decTObin();
         Timer timer = new Timer();

           
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                Date datahora = new Date();
        List<String> JLhora = bin.decToBinary(Integer.parseInt(new SimpleDateFormat("HH").format(datahora)));
        if (JLhora.get(1).equalsIgnoreCase("0")) {
            CBhora0.setSelected(false);
        } else {
            CBhora0.setSelected(true);
        }
        if (JLhora.get(2).equalsIgnoreCase("0")) {
            CBhora1.setSelected(false);
        } else {
            CBhora1.setSelected(true);
        }
        if (JLhora.get(3).equalsIgnoreCase("0")) {
            CBhora2.setSelected(false);
        } else {
            CBhora2.setSelected(true);
        }
        if (JLhora.get(4).equalsIgnoreCase("0")) {
            CBhora3.setSelected(false);
        } else {
            CBhora3.setSelected(true);
        }
        if (JLhora.get(5).equalsIgnoreCase("0")) {
            CBhora4.setSelected(false);
        } else {
            CBhora4.setSelected(true);
        }

        List<String> JLminuto = bin.decToBinary(Integer.parseInt(new SimpleDateFormat("mm").format(datahora)));
        if (JLminuto.get(0).equalsIgnoreCase("0")) {
            CBminuto0.setSelected(false);
        } else {
            CBminuto0.setSelected(true);
        }
        if (JLminuto.get(1).equalsIgnoreCase("0")) {
            CBminuto1.setSelected(false);
        } else {
            CBminuto1.setSelected(true);
        }
        if (JLminuto.get(2).equalsIgnoreCase("0")) {
            CBminuto2.setSelected(false);
        } else {
            CBminuto2.setSelected(true);
        }
        if (JLminuto.get(3).equalsIgnoreCase("0")) {
            CBminuto3.setSelected(false);
        } else {
            CBminuto3.setSelected(true);
        }
        if (JLminuto.get(4).equalsIgnoreCase("0")) {
            CBminuto4.setSelected(false);
        } else {
            CBminuto4.setSelected(true);
        }
        if (JLminuto.get(5).equalsIgnoreCase("0")) {
            CBminuto5.setSelected(false);
        } else {
            CBminuto5.setSelected(true);
        }

        List<String> JLsegundo = bin.decToBinary(Integer.parseInt(new SimpleDateFormat("ss").format(datahora)));
        if (JLsegundo.get(0).equalsIgnoreCase("0")) {
            JCK_seg_0.setSelected(false);
        } else {
            JCK_seg_0.setSelected(true);
        }
         if (JLsegundo.get(1).equalsIgnoreCase("0")) {
            JCK_seg_1.setSelected(false);
        } else {
            JCK_seg_1.setSelected(true);
        }
          if (JLsegundo.get(2).equalsIgnoreCase("0")) {
            JCK_seg_2.setSelected(false);
        } else {
            JCK_seg_2.setSelected(true);
        }
           if (JLsegundo.get(3).equalsIgnoreCase("0")) {
            JCK_seg_3.setSelected(false);
        } else {
            JCK_seg_3.setSelected(true);
        }
            if (JLsegundo.get(4).equalsIgnoreCase("0")) {
            JCK_seg_4.setSelected(false);
        } else {
            JCK_seg_4.setSelected(true);
        }
             if (JLsegundo.get(5).equalsIgnoreCase("0")) {
            JCK_seg_5.setSelected(false);
        } else {
            JCK_seg_5.setSelected(true);
        }
             
             }
        }, 0, 1000);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBhora0;
    private javax.swing.JCheckBox CBhora1;
    private javax.swing.JCheckBox CBhora2;
    private javax.swing.JCheckBox CBhora3;
    private javax.swing.JCheckBox CBhora4;
    private javax.swing.JCheckBox CBminuto0;
    private javax.swing.JCheckBox CBminuto1;
    private javax.swing.JCheckBox CBminuto2;
    private javax.swing.JCheckBox CBminuto3;
    private javax.swing.JCheckBox CBminuto4;
    private javax.swing.JCheckBox CBminuto5;
    private javax.swing.JCheckBox JCK_seg_0;
    private javax.swing.JCheckBox JCK_seg_1;
    private javax.swing.JCheckBox JCK_seg_2;
    private javax.swing.JCheckBox JCK_seg_3;
    private javax.swing.JCheckBox JCK_seg_4;
    private javax.swing.JCheckBox JCK_seg_5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
